COLUMNS_SELECTION_DROPDOWN = 'columns-selection-dropdown'
PREPROC_MULTI_DROPDOWN = 'preproc-multi-dropdown'
CLUSTERING_DROPDOWN = 'clustering-dropdown'
RUN_BUTTON = 'run-button'
TEST_TEXT_BUTTON = 'test-text-button'